default_provider = "age"

[providers.age]
type = "age"
recipients = ["age17lxmh7tvr53knmye359ve5ltntys74sn4np2s0ysg94kxvxnp5hqmc88aw"]

[secrets.ADVENT_OF_CODE_SESSION]
provider = "age"
if_missing = "warn"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU0d2R2VaT2hDOEltSHNhUld4Y3hNck9FMFpWZnBDSURFeitlUityb1dZCkRBSnZ3YUpqYVMzbThFVzZ6am1vWHZLVTFWQnRNUm1mbWNVKyszRW9oMEkKLT4gITNNOlc/RkItZ3JlYXNlIC18WlBuO08gdjJDezV2eApvRVdJdDNsc0h0SXY0Tk9PSkV4bzJUTDVwZVRUMktrbGlIQk9pOFRmb2JhQVZCUVRaVGtFV215M05WY0UyRWZUClN2U1R0RWM2U0FhaEhmb2dwUmpLRlkvdVhVZ1lHR0d0QnptUERMaGQwVG80YlEKLS0tIElQT3NGTGJqbFF3dFowaUV4L0JGQmJ3TlpPWmV4YTM2cDZXVVNkcUh5VlUKJ8Oskyt/84M/HrmiRKLokBo2lwlZcFjeV10YCjWD8Z9bdCCiBGDADl68VuKR1cuseuW/z4gT4+DJmjCCUu15wqbSplyET5/TMriEnel7wJGlz7/FRFuKgpwMQJ53d9ppqXRGVn19h+uSQWYYgwM3qtQtPNJQ9tffO08DK9rvt44GgtYUc3ZNUsS1JP4vb4QyE/KgZCnlJHr4NzzwEdNo9g=="
